### ISSUE TITLE
Code Licence

### ISSUE THREAD

**Issue by hulecom** [jgte/grace-data#1]
Dear programmer,

I'm starting a project with GRACE data and I found your code interesting. Do you agree if I take inspiration from it and if I copy some part?
You might add a Licence to your code to make this official.

Thanks you,
Hulecom

**Comment by jgte** [comment]
Hello,

Please go ahead, I have included a license file now. I may consider forking the repository and starting from there.

I also recommend this [python script](https://github.com/tsutterley/read-GRACE-harmonics/blob/main/doc/source/user_guide/podaac_grace_sync.md) from [another developer](https://github.com/tsutterley); although I never used it, it seems to handle many more data types.

Best regards.

João Encarnação

**Comment by hulecom** [comment]
Thanks for the advice, I had identified tsutterley's git repository during my search but it's even more complete than what I expected.

Best regards,
Hulecom
